services:
  - type: web
    name: voice-assistant
    env: python
    plan: free
    buildCommand: |
      ./install_espeak.sh
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python3.12
